### PR TITLE
install-setuid target

### PR DESCRIPTION
**Pull request by haampie**
Convenience target to make ste setuid:

```
make
sudo make install-setuid prefix=...
```

Depends on #11

### CODE REVIEW

**Comment by fabiensanglard** [comment]
Can you please squash all your changes in one commit? Some commit changes each others and it is difficult to review.

**Comment by haampie** [comment]
done ^

**Comment by denilsonsa** [comment]
Please check if it behaves as expected and if it doesn't introduce any vulnerability when installing as setuid.

When requiring `sudo`, only users who already have super-user access can run the tool. However, installing as setuid means any user can run this tool as super-user, and since this tool essentially launches any arbitrary command, it can allow any user to run any arbitrary command as super-user. Yikes!

Let's look at the code: https://github.com/fabiensanglard/st/blob/8e680b674ef259e03b569ef7badec426c8622844/code/src/utils.cpp#L36-L39
The code checks for a couple of sudo-related env variables. If they are not there, the code doesn't try dropping any root privileges, which is precisely the vulnerability I was talking about. In fact, we can test it right now:

    $ sudo ./ste-without-setuid whoami
    EXEC: [ whoami]
    denilsonsa             ← Good
    Num threads = 1
    Num process = 1
    …
    
    $ ./ste-with-setuid whoami
    EXEC: [ whoami]
    root                   ← DANGER
    Num threads = 1
    Num process = 1
    …

So, before merging this PR, the code must be updated to properly drop privileges when launched without sudo.

**Comment by haampie** [comment]
Something along the lines of

```
diff --git a/code/include/utils.h b/code/include/utils.h
index 6db3dda..62a0bb8 100644
--- a/code/include/utils.h
+++ b/code/include/utils.h
@@ -4,8 +4,9 @@
 
 #include <sys/time.h>
 #include <sys/resource.h>
+#include <sys/types.h>
 
 uint64_t GetTimeMs();
 uint64_t toMs(struct timeval &val);
 void Log(const char *fmt, ...);
-void DropRoot();
+void DropRoot(uid_t uid);
diff --git a/code/src/main.cpp b/code/src/main.cpp
index 29e676f..c374f4c 100644
--- a/code/src/main.cpp
+++ b/code/src/main.cpp
@@ -15,7 +15,7 @@
 
 static constexpr int kSnapshotEveryMs = 1;
 
-int ForkAndExec(char *cmd, char **parameters, int numParameters) {
+int ForkAndExec(char *cmd, char **parameters, int numParameters, uid_t uid) {
     Log("ForkAndExec %s", cmd);
     std::string cmdline = std::string();
     for (int i = 0; i < numParameters; i++) {
@@ -27,7 +27,7 @@ int ForkAndExec(char *cmd, char **parameters, int numParameters) {
     int pid = fork();
     if (pid == 0) { // This is the new process
         // Drop superuser privileges
-        DropRoot();
+        DropRoot(uid);
 
         // We cannot reuse parameters as it, since it is not null terminated
         char *argv[numParameters + 1];
@@ -54,6 +54,8 @@ int ForkAndExec(char *cmd, char **parameters, int numParameters) {
 }
 
 int main(int argc, char **argv) {
+    uid_t uid = getuid();
+
     for (int i = 1; i < argc; i++) {
         // stop on positional arguments
         if (argv[i][0] != '-') break;
@@ -83,6 +85,11 @@ int main(int argc, char **argv) {
         return 0;
     }
 
+    if (setreuid(0, 0) != 0) {
+        fprintf(stderr, "Failed to setreuid\n");
+        exit(EXIT_FAILURE);
+    }
+
     InitOutput();
 
     int netlink_socket = InitNetlink();
@@ -106,7 +113,7 @@ int main(int argc, char **argv) {
     // From here, we are receiving netlink events. We can create the process we want to observe.
     // We add the forked process to the list of Tracked processes.
     uint64_t startTimeMs = GetTimeMs();
-    int pid = ForkAndExec(argv[1], &argv[1], argc - 1);
+    int pid = ForkAndExec(argv[1], &argv[1], argc - 1, uid);
 
     int64_t nextMemorySnapshot = GetTimeMs() - kSnapshotEveryMs;
 
@@ -149,7 +156,7 @@ int main(int argc, char **argv) {
     }
     close(netlink_socket);
 
-    DropRoot();
+    DropRoot(uid);
 
     GenerateOutputs(pid, startTimeMs);
 
diff --git a/code/src/utils.cpp b/code/src/utils.cpp
index 03ef925..cd162ec 100644
--- a/code/src/utils.cpp
+++ b/code/src/utils.cpp
@@ -30,51 +30,9 @@ void Log(const char *fmt, ...) {
     va_end(args);
 }
 
-void DropRoot() {
-    const char *sudo_uid = secure_getenv("SUDO_UID");
-    const char *sudo_gid = secure_getenv("SUDO_GID");
-    if (sudo_uid == nullptr || sudo_gid == nullptr) {
-        // Not running with sudo, user is root and nothing we can drop here.
-        return;
-    }
-
-    // no need to "drop" the privileges we don't have in the first place!
-    if (getuid() != 0) {
-        return;
-    }
-
-    // when invoked with sudo, getuid() will return 0 and we won't be able to drop your privileges
-    uid_t uid;
-    if ((uid = getuid()) == 0) {
-        uid = (uid_t) strtoll(sudo_uid, nullptr, 10);
-//        if (errno != 0) {
-//            perror("under-/over-flow in converting `SUDO_UID` to integer");
-//            exit(EXIT_FAILURE);
-//        }
-    }
-
-    // again, in case we were invoked using sudo
-    gid_t gid;
-    if ((gid = getgid()) == 0) {
-        gid = (gid_t) strtoll(sudo_gid, nullptr, 10);
-//        if (errno != 0) {
-//            perror("under-/over-flow in converting `SUDO_GID` to integer");
-//            exit(EXIT_FAILURE);
-//        }
-    }
-
-    if (setgid(gid) != 0) {
-        perror("setgid");
-        exit(EXIT_FAILURE);
-    }
-    if (setuid(uid) != 0) {
-        perror("setgid");
-        exit(EXIT_FAILURE);
-    }
-
-    // check if we successfully dropped the root privileges
-    if (setuid(0) == 0 || seteuid(0) == 0) {
-        printf("could not drop root privileges!\n");
+void DropRoot(uid_t uid) {
+    if (setresuid(uid, uid, uid) != 0) {
+        fprintf(stderr, "dropping privileges failed\n");
         exit(EXIT_FAILURE);
     }
 }
```

perhaps?

**Comment by denilsonsa** [comment]
I'm also not super-familiar with the APIs, so I'm not sure if this is the best approach.

However, this latest commit changed the `sudo` behavior. Not sure if it's good or bad. Look:

```
$ whoami
denilsonsa

$ sudo whoami
root

$ ./ste-setuid whoami
EXEC: [ whoami]
denilsonsa
…

$ sudo ./ste whoami
EXEC: [ whoami]
root
…
```

This means the command will be running as root, when `ste` is invoked from `sudo`, and that wasn't @fabiensanglard's original behavior. I can't decide if it's better. It looks more consistent, though.

**Comment by haampie** [comment]
To me this behavior looks better. If you run a command under `sudo`, I would expect the subprocesses to run as root too.

**Comment by fabiensanglard** [comment]
As of d086dfd23a392a2d9df00c504c57a9e756a19467 there are four ways to run `ste`.

- No root privileges -> `ste` fails because it needs it.
- Using sudo -> `ste` drops privileges to run the command.
- Using set-user-id -> `ste` drops privileges to run the command.
- In the case user needs to run a command as root, then they can `sudo bash` to make sure there is nothing dropable.

I don't think it is common for an user to want a command to run as root. And I would rather protect users from the common case where `ste` is run via `sudo` or when it is installed with `set-user-id`.

**Comment by fabiensanglard** [comment]
If you want to submit an individual PR for the `Makefile` install with set-user-id, I would gladly merge it.

**Comment by glitsj16** [comment]
> As of d086dfd there are four ways to run ste.
    No root privileges -> ste fails because it needs it.
    Using sudo -> ste drops privileges to run the command.
    Using set-user-id -> ste drops privileges to run the command.
    In the rare case user needs to run a command as root, they can sudo bash to make sure privileges can't be dropped.

An alternative approach to mitigate setuid vulnerabilities is to use a second group on the ste binary:

```sh
chown root:ste /usr/bin/ste
chmod 4750 /usr/bin/ste
```

That way admins have a way to limit access to the setuid binary via standard groupadd procedure.

**Pull request closed without merging**
